In [38]:
#In our dataset, we have recorded systolic blood pressure, cholesterol, glucose levels, activity minutes, and age, along with participants’ smoking habits and disease status. Additionally, each participant was assigned to either Treatment A or Treatment B. As a first step, we will examine whether the below categories are associated.” This can be determined by Chi square test.
#1. Smoker & Disease
#2. Gender & Disease
#3. Treatment & Disease

In [35]:
import pandas as pd
import numpy as np
from scipy.stats import chi2_contingency

In [36]:
df = pd.read_csv(r"C:\Users\hp\Downloads\Effect of smoking on the diseased condition_chi2test.csv")
df.head(5)


id gender smoker treatment disease  age   bmi  systolic_bp  cholesterol  \
0   1      F     No         A      No   63  19.3        113.9        150.9   
1   2      M     No         B      No   33  17.6        105.1        134.4   
2   3      F     No         B     Yes   28  17.8        111.9        120.8   
3   4      M     No         B      No   55  17.2        121.0        148.6   
4   5      M     No         A      No   43  21.6        130.1        147.1   

   glucose  activity_mins  
0     80.6           59.7  
1     74.8           77.8  
2     78.8           78.8  
3     65.5           52.7  
4     69.9           48.8

In [37]:
#1. Smoker & Disease

#Setting up Hypothesis

#Null Hypothesis (H₀): Smoking and disease status are independent (no association).
#Alternative Hypothesis (H₁): Smoking and disease status are associated.

In [41]:
contingency = pd.crosstab(df["smoker"], df["disease"])
print(contingency)

# Chi-square test
chi2, p, dof, expected = chi2_contingency(contingency, correction = True)

print("Chi2 Statistic:", chi2)
print("p-value:", p)
print("Degrees of Freedom:", dof)
print("Expected Frequencies:\n", expected)

disease  No  Yes
smoker          
No       25    8
Yes       4    3
Chi2 Statistic: 0.28715276364179176
p-value: 0.5920509101896898
Degrees of Freedom: 1
Expected Frequencies:
 [[23.925  9.075]
 [ 5.075  1.925]]


In [42]:
#Interpretation

#Since p = 0.592 > 0.05, we fail to reject the null hypothesis (H₀).
#This means: in this dataset, there is no statistically significant association between smoking status and disease occurrence.
#In plain words: whether someone smokes or not does not appear to affect their disease status (based on these 40 observations).

In [43]:
#2. Gender & Disease

#Setting up Hypothesis

#Null Hypothesis (H₀): Gender & Disease status are independent (no association).
#Alternative Hypothesis (H₁): Gender & Disease status are associated.

In [44]:
contingency = pd.crosstab(df["gender"], df["disease"])
print("Contingency Table:\n", contingency)

# Chi-square test
chi2, p, dof, expected = chi2_contingency(contingency)

print("\nChi2 Statistic:", chi2)
print("p-value:", p)
print("Degrees of Freedom:", dof)
print("Expected Frequencies:\n", expected)

Contingency Table:
 disease  No  Yes
gender          
F        14   11
M        15    0

Chi2 Statistic: 7.03030303030303
p-value: 0.00801417905984472
Degrees of Freedom: 1
Expected Frequencies:
 [[18.125  6.875]
 [10.875  4.125]]


In [ ]:
#Interpretation

#Since p = 0.008 < 0.05, we reject the null hypothesis (H₀).
#This means: in this dataset, there is statistically significant association between Gender and disease occurrence.
#In plain words: In this dataset, gender seems to play a role in whether a person has the disease. Females are more likely to have the disease than expected, while males are less likely.

In [ ]:
#3. Treatment & Disease

#Setting up Hypothesis

#Null Hypothesis (H₀): Treatment & Disease status are independent (no association).
#Alternative Hypothesis (H₁): Treatment & Disease status are associated.

In [45]:
contingency = pd.crosstab(df["treatment"], df["disease"])
print("Contingency Table:\n", contingency)

# Chi-square test
chi2, p, dof, expected = chi2_contingency(contingency)

print("\nChi2 Statistic:", chi2)
print("p-value:", p)
print("Degrees of Freedom:", dof)
print("Expected Frequencies:\n", expected)


Contingency Table:
 disease    No  Yes
treatment         
A          16    7
B          13    4

Chi2 Statistic: 0.01571406809964003
p-value: 0.9002419053318376
Degrees of Freedom: 1
Expected Frequencies:
 [[16.675  6.325]
 [12.325  4.675]]


In [ ]:
#Interpretation

#Since p = 0.900 > 0.05, we fail to reject the null hypothesis (H₀).
#This means: in this dataset, there is no statistically significant association between Treatment and Disease occurrence.